### ISSUE TITLE
Cannot link to anchor element on same page.

### ISSUE THREAD

**Issue by TimCadieux** [saaratrix/asp.net-core-mvc-localized-routing#31]
Attempting to use TagHelpers to recreate `<a href="/#about">@Localizer["About"]</a>`

When switching language from English to French

`<a asp-controller="home" asp-action="index" asp-fragment="about">@Localizer["About Us"]</a>`
which renders
`<a href="/en/home#about">À propos de nous</a>`
Which is incorrect as the path is English but the Localised text is French

`<a asp-controller="home" asp-action="index" cms-culture="@ViewData["culture"]" asp-fragment="about">@Localizer["About Us"]</a>`
which renders
`<a href="/fr/accueil">Accueil</a>`

 <a asp-controller="home" asp-action="index" cms-culture="" asp-fragment="about">@Localizer["About Us"]</a>
which renders
`<a href="/fr/accueil">Accueil</a>`

`<a asp-controller="home" asp-action="index" cms-culture=""  cms-keep-link="true" asp-fragment="about">@Localizer["About Us"]</a>`
which renders
<a href="/fr/accueil">À propos de nous</a>

Unsure what to try next.

**Comment by saaratrix** [comment]
I don't believe that fragments are supported by the url rewriter because it sadly has it's own custom solution because at least in 2.x I couldn't figure out how to just middleware change the route data. 

```cs
public static LocalizationUrlResult GetUrlResult(TagHelperContext context, string culture)
        {
            string controllerName = context.AllAttributes["asp-controller"].Value as string;
            string actionName = context.AllAttributes["asp-action"].Value as string;

            var urlResult = LocalizationRouteDataHandler.GetUrl(controllerName, actionName, culture);

            Dictionary<string, string> routeValues = GetRouteValues(context.AllAttributes);
            if (routeValues != null)
            {
                urlResult.Url += LocalizationRouteDataHandler.GetOrderedParameters(controllerName, actionName, routeValues);
            }

            return urlResult;
        }

```

Maybe it's as simple as adding 2 lines in `GetUrlResult() ` in the file: https://github.com/saaratrix/asp.net-core-mvc-localized-routing/blob/master/localization/Localization/LocalizationTagHelperUtility.cs
``` 
string fragment = context.AllAttributes["asp-fragment"].Value as string;

urlResult += $"#{fragment}";
```

**Comment by TimCadieux** [comment]
Great.

Perhaps not elegant but the below does work

   `<a asp-controller="home" asp-action="index" asp-fragment="about">@Localizer["About Us"]</a>`

```

        public static LocalizationUrlResult GetUrlResult(TagHelperContext context, string culture)
        {
            string controllerName = context.AllAttributes["asp-controller"].Value as string;
            string actionName = context.AllAttributes["asp-action"].Value as string;
            string fragment = "";

            try
            {
                string fragmentValue = context.AllAttributes["asp-fragment"].Value as string;
                fragment = fragmentValue;
            }
            catch (Exception)
            {
                //throw;
            }

            var urlResult = LocalizationRouteDataHandler.GetUrl(controllerName, actionName, culture);

            Dictionary<string, string> routeValues = GetRouteValues(context.AllAttributes);
            if (routeValues != null)
            {
                urlResult.Url += LocalizationRouteDataHandler.GetOrderedParameters(controllerName, actionName, routeValues);

                if (!string.IsNullOrEmpty(fragment))
                {
                    urlResult.Url += $"#{fragment}";
                }
            }

            return urlResult;
        }
```
