### ISSUE TITLE
How can I receive fully routed url by passing in Controller and Action?

### ISSUE THREAD

**Issue by TimCadieux** [saaratrix/asp.net-core-mvc-localized-routing#33]
I'm using the Azure B2C to authenticate my users.

My SignInController looks like the below...I'd like to be able to pass the allready localised path onto the B2C serviced so that when it return, it would route to the Dashboard page in the corect language.

The below currently only returns the basic Controller/Action

```
            var redirectUrl = Url.Action("Dashboardv1", "Dashboard");

            return Challenge(
                new AuthenticationProperties { RedirectUri = redirectUrl },
                OpenIdConnectDefaults.AuthenticationScheme);
```

**Comment by saaratrix** [comment]
The Url.Action is from the default asp.net UrlHelper class?

If there are no parameters you should be able to use this class to get the finished culture route:
`LocalizationRouteDataHandler.GetUrl(controllerName, actionName, culture);`

Otherwise it's trickier and I'm not sure.

**Comment by TimCadieux** [comment]
This did the job, thank you.
